#!/bin/bash
source $HOME/.bash_profile

if [ -d "$CMPATH/data" ]
then
  mv -f $CMPATH/data $HOME/cellmodeller.data.recovered
fi

rm -rf $CMPATH

conda-env remove -yn cellmodeller

echo 
echo ---------------------------------------------------------------------------------------------------------
echo "CellModeller and its dependencies (including the conda environment) have been removed."
echo
echo "If you had data in your $CMPATH/data folder, it has been copied to "
echo
echo "		$HOME/cellmodeller.data.recovered"
echo
echo "In case you had anything valuable in there you can recover it, or you can simply delete this directory."
echo
echo ---------------------------------------------------------------------------------------------------------
