package:
  name: pyopencl
  version: !!str 2014.1

source:
#  fn: pyopencl-2014.1.tar.gz
#  url: https://pypi.python.org/packages/source/p/pyopencl/pyopencl-2014.1.tar.gz
#  md5: f89d26676aaff01312116caea114f06c
  git_url: http://git.tiker.net/trees/pyopencl.git
  git_tag: v2014.1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyopencl = pyopencl:main
    #
    # Would create an entry point called pyopencl that calls pyopencl.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pytools >=2014.2
    - pytest >=2
    - decorator >=3.2.0
    - mako
    - numpy

  run:
    - python
    - setuptools
    - pytools >=2014.2
    - pytest >=2
    - decorator >=3.2.0
    - mako
    - numpy

#test:
  # Python imports
  #imports:
  #  - pyopencl
  #  - pyopencl.characterize
  #  - pyopencl.compyte

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://mathema.tician.de/software/pyopencl
  license: MIT License
  summary: 'Python wrapper for OpenCL'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
